### ISSUE TITLE
Providing a page loading auto-hide mechanism?

### ISSUE THREAD

**Issue by dmandrioli** [ibm-js/delite#119]
Goal: avoid weird intermediate rendering. 
Previously in dojo mobile it was done by setting visibility:hidden on body.
http://livedocs.dojotoolkit.org/dojox/mobile/faq#why-does-body-in-many-of-tests-html-files-have-style-visibility-hidden

**Comment by cjolif** [comment]
As of today all demos/samples are supposed to implement that themselves. I don't think we have time to create something specific so closing this.
