### ISSUE TITLE
New feature proposal: animated destroy

### ISSUE THREAD

**Issue by sbrunot** [ibm-js/delite#166]
Calling the destroy method of a widget removes it from the dom. Visually, the dom element disappear suddenly.

I think it could be nice to have an _animated destroy_ feature for widgets: it could be, for example, a new `animatedDestroy` method provided by a Mixin. This method would accept animation parameters as input (type of animation, like fade out or collapse, and duration ?). This method would make the widget disappear with the specified animation, and would then destroy it.

**Comment by wkeese** [comment]
No current plans to implement this.
