### ISSUE TITLE
FF 30 displays a performance warning

### ISSUE THREAD

**Issue by seb-pereira** [ibm-js/delite#194]
When I run a deliteful sample on FF 30 desktop I have this message in the console:

*TypeError: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
node.__proto__ = {}; register.js (line 41)*

Not sure if it is new to FF 30 or related to a change on our side.

**Comment by wkeese** [comment]
Still an issue in FF34, but it will go away when FF enables document.registerElement() native support.   It's experimental now: see http://www.tutorialsavvy.com/2014/06/enabling-web-component-feature-in.html.

**Comment by cjolif** [comment]
Then maybe we should close it as won't fix if we know for sure it will go away?

**Comment by wkeese** [comment]
Sure, OK, closing now.
