### ISSUE TITLE
support for <content> and multiple attach points in templates

### ISSUE THREAD

**Issue by lbod** [ibm-js/delite#247]
Creating a custom element declaratively I'd like to include arbitrary HTML as innerHTML enclosed in the widget and also map to the widget/template properties. 
The equivalent in Dijit was widget.containerNode e.g. http://dojotoolkit.org/documentation/tutorials/1.10/templated/

for example i would like to add declarative HTML like so:

```
<some-element fooproperty="foo" barproperty="bar">
   <div attachNode='myWidgetAttachNode'>I am some inner html, I could be very large but I should be a property of the widget, referenceable and HTML</div>
</some-element>

```

and I could both programmatically and declaratively set the value (in the programmatic case using `myWidgetAttachNode`)
## 

This may be a separate issue, it'd be nice to support an array of `containerNode`'s so that declarative nodes could map to many widget properties e.g. 

```
<some-element fooproperty="foo" barproperty="bar">
   <div attachNode='myWidgetAttachNode'>I am some inner html, I could be very large but I should be a property of the widget, referenceable and HTML</div>
   <div attachNode='anotherMyWidgetAttachNode'>I am different HTML</div>

</some-element>

```

**Comment by wkeese** [comment]
Closing this ticket just because so much time has passed and because we're unlikely to ever implement this enhancement.
