### ISSUE TITLE
Requiring .startup()/.destroy hurts interop

### ISSUE THREAD

**Issue by RoystonS** [ibm-js/delite#257]
One of the problems I (and other developers) have had with Dijit in the past is the requirement of calling .startup() on programmatically-invoked widgets, and often having to manage the manual chaining of such invocations.  (.destroy/.destroyRecursive is equally painful, if not more so, usually.)

I recently had to write some code to plug onto the side of our application to check that all our widgets in our DOM had correctly had .startup called on them, and that dead widgets had been .destroy()ed correctly, as this is so tricky to get right. I found quite a number of widgets which hadn't got this right (mostly by third party groups tbh).

So I'm a little surprised to see delite propagating a manual .startup/.destroy system. (See issue #222 for instance.)

Working with .startup() is extra tricky when mixing widgets with other frameworks, which won't pass on such chained calls or participate in this custom widget lifecycle.  Frameworks such as Angular et al, which provide excellent array-based data-binding and repeater controls can happily create and remove widgets, but don't know to call .startup/.destroy, and so interop becomes quite hard.

The Web Components spec - whilst incomplete, obviously - is heading towards [a mechanism which works a little differently from .startup/.destroy](https://w3c.github.io/webcomponents/spec/custom/#types-of-callbacks), namely one that informs the widget of attaches/detaches (without the widget having to chain that information manually).  [Polymer is implementing these callbacks](http://www.polymer-project.org/docs/polymer/polymer.html#lifecyclemethods)  There's nothing manual involved, although admittedly being told that you're detached from the DOM tree doesn't necessarily mean you're never coming back.

Are there any plans to obviate the need for manual calls to .startup/.destroy?  With their presence, I can't quite see how delite widgets will interop well with other Web Component frameworks, especially where delite widgets are constructed by any other framework that doesn't know to call .startup?

**Comment by wkeese** [comment]
Most of this work was completed for 0.6.  For 0.7 I want to:

* remove the startup() method completely (it's currently deprecated)
* reconsider destroy(); in the old days it was mainly used to workaround IE garbage collection problems.  do we still need it?

**Comment by cjolif** [comment]
> reconsider destroy(); in the old days it was mainly used to workaround IE garbage collection problems. do we still need it?

I suspect the only thing we actually need is "detachedCallback" as we still need to un-register things when detaching (like unregister listeners onto another element that we added at attachement time). 

Until now this was done in destroy (trough own) but if destroy does not exist anymore we would need the detach? (which would be good anymore from a custom element compatibility perspective).

**Comment by wkeese** [comment]
I guess so.   But then, how is detachedCallback() called?   The simple way would be to make users call detachedCallback() manually...

**Comment by wkeese** [comment]
I removed startup() completely in #386.

About setting up / removing listeners in attachedCallback() / detachedCallback(): usually it's sufficient to set up listeners when the widget is created, since they are removed automatically when the widget DOM is destroyed.  Since we only support IE9+ I don't think we need to worry about memory leaks much.  The only tricky case is when widget A is listening to widget B.  In that case it probably makes sense to do it in attachedCallback() / detachedCallback() like @cjolif said.   Possibly CustomElement should stop extending decor/Destroyable since this.own() and this.defer() generally aren't used.

I think though regarding this ticket, titled as "Requiring .startup()/.destroy hurts interop", is that attachedCallback() and detachedCallback() need to be called manually.   So I'll leave this ticket open to mull over that more.

**Comment by RoystonS** [comment]
Yes, the issue really was about the need for manual calls into the widgets and what that does when interop'ing with other frameworks.  Great that you've got rid of startup.  It's a massive pain in Dojo 1.x.

So, if I understand things correctly, attached/detachedCallback are sometimes invoked automatically, and sometimes require manual invocation?

**Comment by wkeese** [comment]
Unfortunately the only time the are automatically called is on Chrome, since it supports custom elements natively.

**Comment by wkeese** [comment]
PS: Also, calling attachedCallback() on widget Foo will automatically call attachedCallback() on any widgets in Foo's template.   And likewise for other internal widgets, for example how deliteful/List internally creates ListItem widgets.

**Comment by wkeese** [comment]
Replacing with #392.
