### ISSUE TITLE
FormWidget: infinite recursion if focusNode === root node

### ISSUE THREAD

**Issue by AdrianVasiliu** [ibm-js/delite#294]
The API doc of FormWidget says: "FormWidget requires that `this.focusNode` be a sub-node of the widget, rather than the root node.  This is because of its processing of `tabIndex`." And indeed, failing to obey to this rule (that is, using the root node as focusNode) leads to at least the following trouble:

A call of `setAttribute()` / `getAttribute()` / `hasAttribute()` for aria-related attributes on a widget inheriting from FormValue leads to an infinite recursion. Indeed, the current implementation
```
setAttribute: dcl.superCall(function (sup) {
	return function (name, value) {
		if (/^aria-/.test(name)) {
			this.focusNode.setAttribute(name, value);
		} else {
			sup.call(this, name, value);
		}
	};
}),
```
(https://github.com/ibm-js/delite/blob/master/FormWidget.js#L120 - and analogous for `getAttribute()` / `hasAttribute()`)

is such that an infinite recursion occurs in this case. Now, a focus node being the root node is a misuse according to the FormWidget doc. However:
* In deliteful, Button and ToggleButton do have the focusNode being the root node. 
* Okay, these widgets do not inherit from FormWidget 
* But the future ComboBox would like to inherit from FormWidget and have the root node being the focusNode.

All in one, questions:
* Is there still a strong reason for FormWidget to forbid focusNode being the root node?
* Isn't this a limitation?
* Does this restriction hold in case FormWidget.tabStops is set to ""? See https://github.com/ibm-js/delite/commit/8fdf583a0f5f70a7a61b05ff954d94cbb8cf7a59#diff-a458ea609278b54658eec126442d8c73R69 
* Regardless the decision to keep the restriction, maybe it would still be nice to protect against infinite recursion, say:

```
if (this.focusNode !== this && /^aria-/.test(name)) {
	this.focusNode.setAttribute(name, value);
}
```
?

**Comment by wkeese** [comment]
I'm closing this as wontfix, because (as discussed above) I don't think it's feasible to support properties like `tabIndex` and `disabled` unless `this.focusNode`, or technically, the nodes specified in `this.tabStops`, are all descendants of `this`.

Note that I did add a check to `forEachFocusNode()` to prevent against the infinite recursion case above.  However, although that guards against the infinite recursion, it doesn't actually make things work if `this.focusNode === this`.
