### ISSUE TITLE
popup too small on iPhone 6+ with keyboard open

### ISSUE THREAD

**Issue by AdrianVasiliu** [ibm-js/delite#348]
For the positioning/sizing of the popup when, many efforts have been made (by @wkeese) to workaround the difficulty to compute the available space on iOS, in particular when the virtual keyboard is open. This works quite well, except on iOS 8, as described below.

How to reproduce:
1. Load https://github.com/ibm-js/delite/blob/master/tests/functional/popup.html in Safari / iOS 8.x, for instance starting in portrait orientation.
2. Click/touch the "show giant centered dialog" button.
=> The popup appears with correct size (so far so good):
3. Touch the input element on top of the popup.
=> The keyboard appears and the popup resizes in a manner which leavs too much unused space on the bottom, in particular in landscape orientation (screenshots on iPhone Plus iOS 8.1.2; the situation is pretty much similar on iPhone 6):
![image](https://cloud.githubusercontent.com/assets/1583981/5489883/8e30170e-86cd-11e4-90dc-df946235ea92.png)
![image](https://cloud.githubusercontent.com/assets/1583981/5489915/b7e83c48-86cd-11e4-8502-f5e0a54b71ea.png)

Remarks:
- Differently than #347, this issue holds similarly for delite/popup and for widgets inheriting from delite/HasDropDown.
- The worst situation is in landscape orientation on iPhone Plus with multiple tabs (this is a new feature in Safari)  - the tabbar taking additional space:
  ![image](https://cloud.githubusercontent.com/assets/1583981/5490013/8e4c3276-86ce-11e4-9f47-39a72170e465.png)

**Comment by AdrianVasiliu** [comment]
>>  So I assume this ticket is really about sizing on iPhone 6+ with the keyboard open.

> More exactly, both iPhone 6 and 6+ are concerned. 

Here are screenshots (with the same "giant centered dialog" in tests/functional/popup.html) on Safari / iPhone 6 (iOS 8.1.2), showing that it's not better than on iPhone 6+:

![image](https://cloud.githubusercontent.com/assets/1583981/5611467/52e7f916-94c7-11e4-8880-2b787621cef8.png)

![image](https://cloud.githubusercontent.com/assets/1583981/5611496/995a77de-94c7-11e4-8b15-c3e687056928.png)

On iPhone 5S, in portrait it's all good:

![image](https://cloud.githubusercontent.com/assets/1583981/5611556/62173770-94c8-11e4-9c9a-32d36695ed58.png)

but in landscape it's not good on iPhone 5S either:

![image](https://cloud.githubusercontent.com/assets/1583981/5611739/84a519ae-94ca-11e4-9b61-be008df7d15e.png)

**Comment by wkeese** [comment]
I think the sizing issues are all fixed now.  In 732653a1b1484055c94c2adf6f3d6919df03f01f a11f28a4de20d98a3f8236556dfded6cac6da3e8 I did a bunch more measurements and other code fixes to make things better.   Still no way of knowing if the auto-suggest is on or off (note that it's always turned on for Japanese etc.), so we need to err the side of caution.

Of course, we're not support iOS8 any longer either.
