### ISSUE TITLE
Renaming properties when inherited from another widget

### ISSUE THREAD

**Issue by tkrugg** [ibm-js/delite#351]
let's say i'm building a Sidepane widget, and I would like to inherit from deliteful/Toggle.
That's nice because it gives me for free a nice API to toggle the sidepane and keep track of its state.
While the inherited method `toggle()` makes perfectly sense for a Sidepane widget, the property `checked` sounds too much like we're dealing with a checkbox.

I'm wondering if there's a way to rename that property (to something such as `isVisible`), so that it makes sense in the context of the widget we're composing.

**Comment by cjolif** [comment]
Agreed. If we really have actual cases like that maybe the base class property should be renamed to be more agnostic but I don't think we should invent a new kind of OOP. And if we did that would be more for dcl than delite I supposed. I suggest closing this as won't fix?

**Comment by wkeese** [comment]
OK, sorry @tkrugg but closing this.
