### ISSUE TITLE
Who is the author of the Dojo 2.0 and Emerging Web Standards document?

### ISSUE THREAD

**Issue by dandv** [ibm-js/delite#358]
The [Dojo 2.0 and Emerging Web Standards document](https://docs.google.com/document/d/1kqe3Oq7W6lg-JY_iqMl5G7SxGTD0uQ6FFIoP4KPAkUw) reads a bit funny, alternating between an unnamed "I" and "we".

**Comment by wkeese** [comment]
Looks like I wrote that originally (so that's who "I" is), but the document is a bit dated now.  It's from July 2013.  Perhaps something like http://ibm-js.github.io/2014/07/18/delite-and-deliteful.html supercedes it.

**Comment by cjolif** [comment]
I suspect after https://github.com/ibm-js/delite/pull/359#issuecomment-69708405 we can close this as well?

**Comment by wkeese** [comment]
Ah, right, thanks.
