### ISSUE TITLE
popup: 'show tall drop down button', popup too tall on subsequent opening of the popup 

### ISSUE THREAD

**Issue by lbod** [ibm-js/delite#360]
1. load `delite/tests/functional/popup.html` in your browser
2. resize the browser to the point where the _show tall drop down button_ button shows the popup above the button.
3. once you're at that point, reload the page and launch the _show tall drop down button_ popup
4. close the popup (focussing elsewhere on the page)
5. launch the _show tall drop down button_ popup again you should see the popup obscures the button. 

This is related to https://github.com/ibm-js/delite/issues/347 

The first launch shows:
![screen shot 2015-01-08 at 23 20 44](https://cloud.githubusercontent.com/assets/733371/5672904/3fffebd8-978d-11e4-8068-4c55e2fd2727.png)

The next launch shows:

![screen shot 2015-01-08 at 23 20 59](https://cloud.githubusercontent.com/assets/733371/5672911/54c57e52-978d-11e4-8eb6-3ec0b98b6778.png)

A simple change again is needed to https://github.com/ibm-js/delite/blob/master/popup.js#L422 e.g.

from:

``` js
wrapper.style.height = args._naturalHeight > maxHeight ? maxHeight + "px" : "auto";
```

to:

``` js
wrapper.style.height = args._naturalHeight >= maxHeight ? maxHeight + "px" : "auto";
```

**Comment by wkeese** [comment]
Again, your change doesn't look right.   The naturalHeight should be something like 2000, and the maxHeight should be something like 400, so `>` and `>=` should return the same result.

**Comment by wkeese** [comment]
This works correctly now; it actually started working correctly in ee21727aaf22a673cee6f74276c5a5140d112bbf.
