### ISSUE TITLE
delite/KeyNav: misbehavior when focusDescendants is set to false after initialization

### ISSUE THREAD

**Issue by AdrianVasiliu** [ibm-js/delite#375]
In its postRender(), KeyNav installs event handlers for "delite-deactivated" and "focusin" conditionally, only if `focusDescendants` is true (default value), and these handlers are NOT removed if `focusDescendants` is later set to false (while the doc doesn't say it should not be changed after initialization, and in Combobox case it can only be changed after List's initialization).

I think KeyNav.refreshRendering() should take care of installing/uninstalling these handlers depending on the current value of `focusDescendants`. Alternatively (but less optimal I guess), the handlers could be made no-op when `this.focusDescendants` is false.

**Comment by AdrianVasiliu** [comment]
Submitted #376 for it.

**Comment by cjolif** [comment]
please put 0.6.0 milestones _and_ type of (bug, enhancement...) on issues so that they appear automatically in "release notes".

**Comment by AdrianVasiliu** [comment]
Thanks @wkeese.
@cjolif: done.

**Comment by AdrianVasiliu** [comment]
@wkeese could you please re-release delite with a beta tag (0.6.0-beta.4)?

**Comment by wkeese** [comment]
OK, I did.
