### ISSUE TITLE
Lifecycle events changedAttribute callback

### ISSUE THREAD

**Issue by opinel** [ibm-js/delite#377]
Hi,

Thanks for your great work on getting custom elements in today's browsers.
If I am not mistaken, you are supporting the create / attach / detach callbacks of the Custom Element spec. I was wondering why you do not support the changedAttribute callback? 
Is there a particular technical reason for this decision or was there no explicit use case?

Thanks

/Frank

**Comment by wkeese** [comment]
There is a technical reason, and there's a long discussion at #343.   Basically, it's hard to monitor changes to special properties (like dir and tabIndex) in a cross-platform performant way.
