### ISSUE TITLE
can't load delite through Dojo's require

### ISSUE THREAD

**Issue by mc007** [ibm-js/delite#384]
Hi,
is there a trick to get delite working with dojo's require ? Its crashing at every corner (handlebars, css, theme) due the missing require::config support. I don't want to bother you with this, if its incompatible to Dojo, I can figure out another way :-)

thanks.

**Comment by wkeese** [comment]
Delite (and all the ibm-js code) needs to be loaded through requirejs.   No plans to support other loaders at this time.

Note that dojo modules can also be loaded through requirejs.

**Comment by mc007** [comment]
ouch, this is very very bad for me. i am screwed then. 
anyways, thanks for the heads up.

**Comment by mc007** [comment]
please put this somewhere in the docs that there is an incompatibility. i wasted a full day just for this. 
g

**Comment by wkeese** [comment]
You are not screwed.   As I already said, just use requirejs.

**Comment by mc007** [comment]
the problem is that i still need to load dojo.js for some reasons. anyway, will try again later. 
thank you.

**Comment by wkeese** [comment]
OK.   I don't know why you need to load dojo.js.   Maybe you just need to require() dojo/_base/kernel or other modules in dojo/_base.

**Comment by mc007** [comment]
Yeah, got it working, finally. i had to change quite some stuff in maqetta-2 for deliteful :-)
ash on my head, and thank you again!
