### ISSUE TITLE
delite/features uses window and it is breaking the build.

### ISSUE THREAD

**Issue by clmath** [ibm-js/delite#401]
This is the same issue as https://github.com/ibm-js/delite/issues/241.

The line here [features#L22](https://github.com/ibm-js/delite/blob/master/features.js#L22) should be modified to check if `window` exist before using it or be wrapped in a function like at [features#L24](https://github.com/ibm-js/delite/blob/master/features.js#L24) since function for has tests won't be evaluated at build time. 

Another solution would be to wrap all the browser only tests in a `if` statement like it is done in [deliteful/features](https://github.com/ibm-js/deliteful/blob/master/features.js#L61).

**Comment by wkeese** [comment]
Thanks, I'll fix.

**Comment by clmath** [comment]
Actually the fix is not good. There is a typo in the condition here https://github.com/ibm-js/delite/commit/4b3b33f39281bc3c490730a2479c221f0542e0a4#diff-31269337867008f33aa993b7b50c3a3eR12

It should be `typeof window !== "undefined"`.

I think we will have to release a 0.7.1 with the fix and then proceed with the build.
