### ISSUE TITLE
DisplayContainer: Do no remove child on hide

### ISSUE THREAD

**Issue by EAlexRojas** [ibm-js/delite#407]
On the show method is understandable that if the element is not a child of the widget, it has to add it.

But on the hide method, if the element is actually a child of the widget, it's really needed to remove it from the DOM?  Maybe the child has to be removed only if it has been added on the show method? 

or maybe hide method doesn't have to remove the element ?

**Comment by wkeese** [comment]
ISTM typically show() and hide() just show and hide the element, rather than adding/removing it from the DOM.   Removing and then re-adding elements every time they are hidden/shown seems unnecessarily expensive because it will trigger calls to removedCallback()/attachedCallback() for all the widgets contained in the element

**Comment by wkeese** [comment]
Ah, I misunderstood.   I agree w/what you originally wrote/implied, that it's weird to remove the element every time.

**Comment by cjolif** [comment]
Before I start implementing something we need to decide what. I guess there are two options:

1. We remove the element only if was added by us (so we need to keep track of that information)
2. We remove the element only if a particular param is passed to hide like { remove: true }.

What do people think?

**Comment by wkeese** [comment]
I think you should pick option 3: never remove the element.

Why?   Because the method is called "hide", not "remove", and also because I don't know of any cases where applications actually want to remove the element.   Is there something I missed?

**Comment by mc007** [comment]
removing when hide is called would be really annoying, indeed, same for show. 
also, please don't call 'select' (followed by show/onShow) when adding something to a container. in dijit this caused lots of performance in some cases.

**Comment by cjolif** [comment]
@wkeese the reason remove is here is that users have asked for it (cc: @edchat) in a application framework you might want to unload views that where dynamically added. So it seems 2. is the solution. This allows the ones that want to remove it (the use-case I just mentioned) to get it removed and for your own use-case it will never be removed as I delite/deliteful elements (outside of dapp) will never put that parameter on.

**Comment by edchat** [comment]
@cjolif we have had users ask for the ability to unload views in dapp, and we have implemented it there, but dapp did not expect it to happen automatically on hide (that would be a bad idea).  It could happen conditionally on hide, but support to unload a view separately from hide may be more useful.  dapp has support for the app to request a view to be unloaded currently, and had plans to be able to setup a maxChildren type of flag which if set would mean we would remove the oldest child view when the max is exceeded.  So from dapp's perspective, I don't think the flag to remove the view is required, we could use it in the one case where the view which is currently showing is the one to be removed, but we would still need to support the ability to remove other views.

**Comment by cjolif** [comment]
Ok, then even if dapp don't need this I'll remove it entirely.
