### ISSUE TITLE
recommended way to store data per widget?

### ISSUE THREAD

**Issue by gbaumgart** [ibm-js/delite#456]
Hi,

do you have by chance a recommendation where/how to store any sort of data for widgets ? Using dom-attributes works for simple things but not if you want store JS (event handlers, store data,...) or CSS (states) for that widget. 

Currently I am saving additional data for widgets as custom HTML element (derived from delite/CustomElement) within the widet's dom node:

```xml
<button is="d-button" label="Blue-Ray">
<d-xscript targetevent="click" block="command://deviceScope=system_devices&device=e5a06e24-6aa4-c8c5-3ffc-9d84d8528a91&driver=235eb680-cb87-11e3-9c1a-0800200c9a66&driverScope=system_drivers&block=53a10527-709b-4c7d-7a90-37f58f17c8db" script="PowerOn"></d-xscript>
</button>
```

Problem with that is that some widgets need to be recomposed for being a "delite/Container" via require.config.map and that feels already a little too hacky and I'd like to know other options. Possibly it was not part of the design and I have to add such feature just myself (no problem).

Thanks for any hint.

**Comment by wkeese** [comment]
But you can assign any arbitrary data as Element properties (not attributes, but properties).   I don't see what the issue is.  Just say `myButton.complexData = {foo: 123}` type of thing?

**Comment by gbaumgart** [comment]
its about de/serializing widgets into clean & editable HTML. in my case, i need to save anything as childs into any deliteful widget.

**Comment by gbaumgart** [comment]
so, just to make some more example:

<button is="d-button" label="Volume Down" state="on">

        
        <d-xscript style="position:relative" targetevent="click" block="command://deviceScope=system_devices.."/>

        
        <d-xstate-css name="on">
            .state {
                border: 2px solid #333029;
            }
            .conditionalExtraState_myarg {
                border: 2px solid #333029;
            }
        </d-xstate-css>

        
        <d-xstate-style name="off" style="border: none"/>

        
        <d-xstate-script name="error" style="border: red">
          {
              some script or json
          }
        <d-xstate-script>

    </button>
```

since deliteful/button needs to be hacked for being a container, i was wondering what the plan-b would be for users to store data that way with deliteful, that's it :-)

thanks again,
g

**Comment by wkeese** [comment]
I see, that's interesting.   I don't have any "Plan B", but I don't see why you would need Button to be a delite/Container.  It seems like you would just have some Widget initialization step that scanned and applied all `<d-xstate-script>` etc. children.

BTW, you shouldn't use self-closing tags (`<d-xstate-style name="off" style="border: none"/>`) because they won't work on IE.  You need a separate `</d-xstate-style>`.

**Comment by gbaumgart** [comment]
indeed, button doesn't need to be a container anymore in 0.8. i had to do that to make it work with Maqetta sometime.

ok then, another fuss for nothing, sorry again. 

thanks a lot Bill. 

g
