### ISSUE TITLE
Stateful wraps any widget method

### ISSUE THREAD

**Issue by gbaumgart** [ibm-js/delite#459]
Hi,
currently every widget method is currently wrapped by Stateful::introspect. This can have an awful performance penalty. Bill mentioned that I have to specify "properties" somewhere but when looking at the deliteful's built-in widgets, this hasn't been done anywhere. For instance ViewStack:show is also wrapped but it makes no sense at all. 

How can we prevent this? I doubt that I need to define a list for the whole deliteful widget API for not being wrapped, or do I ? 

Is this a design or implementation flaw/mistake ? I am confused.
thanks,
guenter

**Comment by wkeese** [comment]
It's a design decision to make the API nice, but you can override the list for a particular widget by redefining `getPropsToObserve()`.

**Comment by gbaumgart** [comment]
ok, thanks. just to make it clear: I have to define this for all methods of every Deliteful widget, right?  It's even wrapping "on", "emit" ....sorry for bugging but this makes no sense to me. 

Do you know where I can skip that for properties being a function? 

g

**Comment by gbaumgart** [comment]
ah, found the old posts: https://github.com/ibm-js/decor/issues/59
g

**Comment by gbaumgart** [comment]
well, I placed a function check in Stateful::getPropsToObserve and in CustomElement::getPropsToObserve and in Stateful::getProps but still wraps "on" and "emit". My other widget methods however are called directly now. 

So thanks again.

**Comment by wkeese** [comment]
OK good.  I'm not sure what happened with on() and emit() but I sure you could trace it by using the debugger.
